spring.data.mongodb.uri=mongodb://host.docker.internal:27017/demo
spring.data.mongodb.database=demo_db
server.port=8080
push.vapid.public-key=BP-aptrSq9dpOuxr8u_RI2KRAWeDHsropK04usgLeRxhI6i-khaPkER910W8-EvGlTtPsTC3RgaRtK6g_NEhMxA
push.vapid.private-key=PpkeqFOBoe_hN15BRcYGshliu_bBQBNZA8JBAA2m4Lo

