spring.data.mongodb.uri=mongodb://host.docker.internal:27017/demo
spring.data.mongodb.database=demo_db
server.port=8080
push.vapid.public-key=BKRWty7ku1XcQkjaWm3SbIzwbv1LczNLFgJifeUbyWIa8upTB0d_1BCaI4UuEk4-Q6akzMgR4FW3JyIhqpNuNWk
push.vapid.private-key=RWAzrPMvry37XOTYVlirPkSOPVwINyUMFphOiguF_2w
